version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    working_dir: /app
    image: node:18-alpine
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
